[package]
name = "passcheck"
version = "0.2.0"
edition = "2024"
authors = ["Ali <alibalochi1910@gmail.com>"]
description = "A flexible rule-base password validation library"
license = "MIT"
repository = "https://github.com/ALIasgharBalochi/passcheck"
readme = "README.md"
[dependencies]
